export interface Broker {
  code: string;
  name: string;
}

// Retrieved from https://www.idx.co.id/id/data-pasar/ringkasan-perdagangan/ringkasan-broker
export const brokers: Broker[] = [
  { code: "AD", name: "Sukadana Prima Sekuritas" },
  { code: "AF", name: "Harita Kencana Sekuritas" },
  { code: "AG", name: "Kiwoom Sekuritas Indonesia" },
  { code: "AH", name: "Shinhan Sekuritas Indonesia" },
  { code: "AI", name: "Kay Hian Sekuritas" },
  { code: "AK", name: "UBS Sekuritas Indonesia" },
  { code: "AO", name: "ERDIKHA ELIT SEKURITAS" },
  { code: "AP", name: "Pacific Sekuritas Indonesia" },
  { code: "AR", name: "Binaartha Sekuritas" },
  { code: "AT", name: "Phintraco Sekuritas" },
  { code: "AZ", name: "Sucor Sekuritas" },
  { code: "BB", name: "Verdhana Sekuritas Indonesia" },
  { code: "BF", name: "Inti Fikasa Sekuritas" },
  { code: "BK", name: "J.P. Morgan Sekuritas Indonesia" },
  { code: "BQ", name: "Korea Investment and Sekuritas Indonesia" },
  { code: "BR", name: "Trust Sekuritas" },
  { code: "BS", name: "Equity Sekuritas Indonesia" },
  { code: "CC", name: "MANDIRI SEKURITAS" },
  { code: "CD", name: "Mega Capital Sekuritas" },
  { code: "CP", name: "KB Valbury Sekuritas" },
  { code: "DD", name: "Makindo Sekuritas" },
  { code: "DH", name: "SINARMAS SEKURITAS" },
  { code: "DP", name: "DBS Vickers Sekuritas Indonesia" },
  { code: "DR", name: "RHB Sekuritas Indonesia" },
  { code: "DU", name: "KAF Sekuritas Indonesia" },
  { code: "DX", name: "Bahana Sekuritas" },
  { code: "EL", name: "Evergreen Sekuritas Indonesia" },
  { code: "EP", name: "MNC Sekuritas" },
  { code: "ES", name: "EKOKAPITAL SEKURITAS" },
  { code: "FO", name: "Forte Global Sekuritas" },
  { code: "FS", name: "Yuanta Sekuritas Indonesia" },
  { code: "FZ", name: "Waterfront Sekuritas Indonesia" },
  { code: "GA", name: "BNC Sekuritas Indonesia" },
  { code: "GI", name: "Webull Sekuritas Indonesia" },
  { code: "GR", name: "PANIN SEKURITAS Tbk." },
  { code: "HD", name: "KGI Sekuritas Indonesia" },
  { code: "HP", name: "Henan Putihrai Sekuritas" },
  { code: "IC", name: "Integrity Capital Sekuritas" },
  { code: "ID", name: "Anugerah Sekuritas Indonesia" },
  { code: "IF", name: "SAMUEL SEKURITAS INDONESIA" },
  { code: "IH", name: "Indo Harvest Sekuritas" },
  { code: "II", name: "Danatama Makmur Sekuritas" },
  { code: "IN", name: "INVESTINDO NUSANTARA SEKURITA" },
  { code: "IT", name: "INTI TELADAN SEKURITAS" },
  { code: "IU", name: "Indo Capital Sekuritas" },
  { code: "KI", name: "Ciptadana Sekuritas Asia" },
  { code: "KK", name: "Phillip Sekuritas Indonesia" },
  { code: "KZ", name: "CLSA Sekuritas Indonesia" },
  { code: "LG", name: "Trimegah Sekuritas Indonesia Tbk." },
  { code: "LS", name: "Reliance Sekuritas Indonesia Tbk." },
  { code: "MG", name: "Semesta Indovest Sekuritas" },
  { code: "MI", name: "Victoria Sekuritas Indonesia" },
  { code: "MU", name: "Minna Padi Investama Sekuritas" },
  { code: "NI", name: "BNI Sekuritas" },
  { code: "OD", name: "BRI Danareksa Sekuritas" },
  { code: "OK", name: "NET SEKURITAS" },
  { code: "PC", name: "FAC Sekuritas Indonesia" },
  { code: "PD", name: "Indo Premier Sekuritas" },
  { code: "PF", name: "Danasakti Sekuritas Indonesia" },
  { code: "PG", name: "Panca Global Sekuritas" },
  { code: "PI", name: "Magenta Kapital Sekuritas Indonesia" },
  { code: "PO", name: "Pilarmas Investindo Sekuritas" },
  { code: "PP", name: "Aldiracita Sekuritas Indonesia" },
  { code: "QA", name: "Tuntun Sekuritas Indonesia" },
  { code: "RB", name: "Ina Sekuritas Indonesia" },
  { code: "RF", name: "Buana Capital Sekuritas" },
  { code: "RG", name: "Profindo Sekuritas Indonesia" },
  { code: "RO", name: "Pluang Maju Sekuritas" },
  { code: "RS", name: "Yulie Sekuritas Indonesia Tbk." },
  { code: "RX", name: "Macquarie Sekuritas Indonesia" },
  { code: "SA", name: "Elit Sukses Sekuritas" },
  { code: "SF", name: "Surya Fajar Sekuritas" },
  { code: "SH", name: "Artha Sekuritas Indonesia" },
  { code: "SQ", name: "BCA Sekuritas" },
  { code: "SS", name: "Supra Sekuritas Indonesia" },
  { code: "TF", name: "Laba Sekuritas Indonesia" },
  { code: "TP", name: "OCBC Sekuritas Indonesia" },
  { code: "TS", name: "Dwidana Sakti Sekuritas" },
  { code: "XA", name: "NH Korindo Sekuritas Indonesia" },
  { code: "XC", name: "Ajaib Sekuritas Asia" },
  { code: "XL", name: "Stockbit Sekuritas Digital" },
  { code: "YB", name: "Yakin Bertumbuh Sekuritas" },
  { code: "YJ", name: "Lotus Andalan Sekuritas" },
  { code: "YO", name: "Amantara Sekuritas Indonesia" },
  { code: "YP", name: "Mirae Asset Sekuritas Indonesia" },
  { code: "YU", name: "CGS International Sekuritas Indonesia" },
  { code: "ZP", name: "Maybank Sekuritas Indonesia" },
  { code: "ZR", name: "Bumiputera Sekuritas" },
];
